// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package rpc;

/**
 * Protobuf type {@code rpc.LoginReply}
 */
public final class LoginReply extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:rpc.LoginReply)
        LoginReplyOrBuilder {
    public static final int MESSAGE_FIELD_NUMBER = 1;
    public static final int USER_ID_FIELD_NUMBER = 2;
    public static final int FIRST_NAME_FIELD_NUMBER = 3;
    public static final int LAST_NAME_FIELD_NUMBER = 4;
    public static final int PHONE_FIELD_NUMBER = 5;
    public static final int ADDRESS_FIELD_NUMBER = 6;
    public static final int CARD_NO_FIELD_NUMBER = 7;
    public static final int ACCOUNT_NO_FIELD_NUMBER = 8;
    public static final int CARD_BALANCE_FIELD_NUMBER = 9;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:rpc.LoginReply)
    private static final LoginReply DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<LoginReply>
            PARSER = new com.google.protobuf.AbstractParser<LoginReply>() {
        public LoginReply parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new LoginReply(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new LoginReply();
    }

    private ReplyBaseOuterClass.ReplyBase message_;
    private long userId_;
    private volatile Object firstName_;
    private volatile Object lastName_;
    private volatile Object phone_;
    private volatile Object address_;
    private volatile Object cardNo_;
    private volatile Object accountNo_;
    private volatile Object cardBalance_;
    private byte memoizedIsInitialized = -1;

    // Use LoginReply.newBuilder() to construct.
    private LoginReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private LoginReply() {
        userId_ = 0L;
        firstName_ = "";
        lastName_ = "";
        phone_ = "";
        address_ = "";
        cardNo_ = "";
        accountNo_ = "";
        cardBalance_ = "";
    }

    private LoginReply(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        ReplyBaseOuterClass.ReplyBase.Builder subBuilder = null;
                        if (message_ != null) {
                            subBuilder = message_.toBuilder();
                        }
                        message_ = input.readMessage(ReplyBaseOuterClass.ReplyBase.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(message_);
                            message_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 16: {

                        userId_ = input.readInt64();
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        firstName_ = s;
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        lastName_ = s;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        phone_ = s;
                        break;
                    }
                    case 50: {
                        String s = input.readStringRequireUtf8();

                        address_ = s;
                        break;
                    }
                    case 58: {
                        String s = input.readStringRequireUtf8();

                        cardNo_ = s;
                        break;
                    }
                    case 66: {
                        String s = input.readStringRequireUtf8();

                        accountNo_ = s;
                        break;
                    }
                    case 74: {
                        String s = input.readStringRequireUtf8();

                        cardBalance_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return rpc.UserProto.internal_static_rpc_LoginReply_descriptor;
    }

    public static LoginReply parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static LoginReply parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static LoginReply parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static LoginReply parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static LoginReply parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static LoginReply parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static LoginReply parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static LoginReply parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static LoginReply parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static LoginReply parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static LoginReply parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static LoginReply parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(LoginReply prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static LoginReply getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<LoginReply> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return rpc.UserProto.internal_static_rpc_LoginReply_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        LoginReply.class, Builder.class);
    }

    /**
     * <code>.ReplyBase message = 1;</code>
     */
    public boolean hasMessage() {
        return message_ != null;
    }

    /**
     * <code>.ReplyBase message = 1;</code>
     */
    public ReplyBaseOuterClass.ReplyBase getMessage() {
        return message_ == null ? ReplyBaseOuterClass.ReplyBase.getDefaultInstance() : message_;
    }

    /**
     * <code>.ReplyBase message = 1;</code>
     */
    public ReplyBaseOuterClass.ReplyBaseOrBuilder getMessageOrBuilder() {
        return getMessage();
    }

    /**
     * <code>int64 user_id = 2;</code>
     */
    public long getUserId() {
        return userId_;
    }

    /**
     * <code>string first_name = 3;</code>
     */
    public String getFirstName() {
        Object ref = firstName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            firstName_ = s;
            return s;
        }
    }

    /**
     * <code>string first_name = 3;</code>
     */
    public com.google.protobuf.ByteString
    getFirstNameBytes() {
        Object ref = firstName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            firstName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string last_name = 4;</code>
     */
    public String getLastName() {
        Object ref = lastName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            lastName_ = s;
            return s;
        }
    }

    /**
     * <code>string last_name = 4;</code>
     */
    public com.google.protobuf.ByteString
    getLastNameBytes() {
        Object ref = lastName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            lastName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string phone = 5;</code>
     */
    public String getPhone() {
        Object ref = phone_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            phone_ = s;
            return s;
        }
    }

    /**
     * <code>string phone = 5;</code>
     */
    public com.google.protobuf.ByteString
    getPhoneBytes() {
        Object ref = phone_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            phone_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string address = 6;</code>
     */
    public String getAddress() {
        Object ref = address_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            address_ = s;
            return s;
        }
    }

    /**
     * <code>string address = 6;</code>
     */
    public com.google.protobuf.ByteString
    getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            address_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string card_no = 7;</code>
     */
    public String getCardNo() {
        Object ref = cardNo_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            cardNo_ = s;
            return s;
        }
    }

    /**
     * <code>string card_no = 7;</code>
     */
    public com.google.protobuf.ByteString
    getCardNoBytes() {
        Object ref = cardNo_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            cardNo_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string account_no = 8;</code>
     */
    public String getAccountNo() {
        Object ref = accountNo_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            accountNo_ = s;
            return s;
        }
    }

    /**
     * <code>string account_no = 8;</code>
     */
    public com.google.protobuf.ByteString
    getAccountNoBytes() {
        Object ref = accountNo_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            accountNo_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string card_balance = 9;</code>
     */
    public String getCardBalance() {
        Object ref = cardBalance_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            cardBalance_ = s;
            return s;
        }
    }

    /**
     * <code>string card_balance = 9;</code>
     */
    public com.google.protobuf.ByteString
    getCardBalanceBytes() {
        Object ref = cardBalance_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            cardBalance_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (message_ != null) {
            output.writeMessage(1, getMessage());
        }
        if (userId_ != 0L) {
            output.writeInt64(2, userId_);
        }
        if (!getFirstNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, firstName_);
        }
        if (!getLastNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastName_);
        }
        if (!getPhoneBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, phone_);
        }
        if (!getAddressBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, address_);
        }
        if (!getCardNoBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, cardNo_);
        }
        if (!getAccountNoBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 8, accountNo_);
        }
        if (!getCardBalanceBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 9, cardBalance_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (message_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getMessage());
        }
        if (userId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(2, userId_);
        }
        if (!getFirstNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, firstName_);
        }
        if (!getLastNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastName_);
        }
        if (!getPhoneBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, phone_);
        }
        if (!getAddressBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, address_);
        }
        if (!getCardNoBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, cardNo_);
        }
        if (!getAccountNoBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, accountNo_);
        }
        if (!getCardBalanceBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, cardBalance_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof LoginReply)) {
            return super.equals(obj);
        }
        LoginReply other = (LoginReply) obj;

        boolean result = true;
        result = result && (hasMessage() == other.hasMessage());
        if (hasMessage()) {
            result = result && getMessage()
                    .equals(other.getMessage());
        }
        result = result && (getUserId()
                == other.getUserId());
        result = result && getFirstName()
                .equals(other.getFirstName());
        result = result && getLastName()
                .equals(other.getLastName());
        result = result && getPhone()
                .equals(other.getPhone());
        result = result && getAddress()
                .equals(other.getAddress());
        result = result && getCardNo()
                .equals(other.getCardNo());
        result = result && getAccountNo()
                .equals(other.getAccountNo());
        result = result && getCardBalance()
                .equals(other.getCardBalance());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasMessage()) {
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
        }
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getUserId());
        hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstName().hashCode();
        hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastName().hashCode();
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhone().hashCode();
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
        hash = (37 * hash) + CARD_NO_FIELD_NUMBER;
        hash = (53 * hash) + getCardNo().hashCode();
        hash = (37 * hash) + ACCOUNT_NO_FIELD_NUMBER;
        hash = (53 * hash) + getAccountNo().hashCode();
        hash = (37 * hash) + CARD_BALANCE_FIELD_NUMBER;
        hash = (53 * hash) + getCardBalance().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<LoginReply> getParserForType() {
        return PARSER;
    }

    public LoginReply getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code rpc.LoginReply}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:rpc.LoginReply)
            rpc.LoginReplyOrBuilder {
        private ReplyBaseOuterClass.ReplyBase message_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                ReplyBaseOuterClass.ReplyBase, ReplyBaseOuterClass.ReplyBase.Builder, ReplyBaseOuterClass.ReplyBaseOrBuilder> messageBuilder_;
        private long userId_;
        private Object firstName_ = "";
        private Object lastName_ = "";
        private Object phone_ = "";
        private Object address_ = "";
        private Object cardNo_ = "";
        private Object accountNo_ = "";
        private Object cardBalance_ = "";

        // Construct using rpc.LoginReply.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return rpc.UserProto.internal_static_rpc_LoginReply_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return rpc.UserProto.internal_static_rpc_LoginReply_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            LoginReply.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            if (messageBuilder_ == null) {
                message_ = null;
            } else {
                message_ = null;
                messageBuilder_ = null;
            }
            userId_ = 0L;

            firstName_ = "";

            lastName_ = "";

            phone_ = "";

            address_ = "";

            cardNo_ = "";

            accountNo_ = "";

            cardBalance_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return rpc.UserProto.internal_static_rpc_LoginReply_descriptor;
        }

        public LoginReply getDefaultInstanceForType() {
            return LoginReply.getDefaultInstance();
        }

        public LoginReply build() {
            LoginReply result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public LoginReply buildPartial() {
            LoginReply result = new LoginReply(this);
            if (messageBuilder_ == null) {
                result.message_ = message_;
            } else {
                result.message_ = messageBuilder_.build();
            }
            result.userId_ = userId_;
            result.firstName_ = firstName_;
            result.lastName_ = lastName_;
            result.phone_ = phone_;
            result.address_ = address_;
            result.cardNo_ = cardNo_;
            result.accountNo_ = accountNo_;
            result.cardBalance_ = cardBalance_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof LoginReply) {
                return mergeFrom((LoginReply) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(LoginReply other) {
            if (other == LoginReply.getDefaultInstance()) return this;
            if (other.hasMessage()) {
                mergeMessage(other.getMessage());
            }
            if (other.getUserId() != 0L) {
                setUserId(other.getUserId());
            }
            if (!other.getFirstName().isEmpty()) {
                firstName_ = other.firstName_;
                onChanged();
            }
            if (!other.getLastName().isEmpty()) {
                lastName_ = other.lastName_;
                onChanged();
            }
            if (!other.getPhone().isEmpty()) {
                phone_ = other.phone_;
                onChanged();
            }
            if (!other.getAddress().isEmpty()) {
                address_ = other.address_;
                onChanged();
            }
            if (!other.getCardNo().isEmpty()) {
                cardNo_ = other.cardNo_;
                onChanged();
            }
            if (!other.getAccountNo().isEmpty()) {
                accountNo_ = other.accountNo_;
                onChanged();
            }
            if (!other.getCardBalance().isEmpty()) {
                cardBalance_ = other.cardBalance_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            LoginReply parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (LoginReply) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        public boolean hasMessage() {
            return messageBuilder_ != null || message_ != null;
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        public ReplyBaseOuterClass.ReplyBase getMessage() {
            if (messageBuilder_ == null) {
                return message_ == null ? ReplyBaseOuterClass.ReplyBase.getDefaultInstance() : message_;
            } else {
                return messageBuilder_.getMessage();
            }
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        public Builder setMessage(
                ReplyBaseOuterClass.ReplyBase.Builder builderForValue) {
            if (messageBuilder_ == null) {
                message_ = builderForValue.build();
                onChanged();
            } else {
                messageBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        public Builder setMessage(ReplyBaseOuterClass.ReplyBase value) {
            if (messageBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                message_ = value;
                onChanged();
            } else {
                messageBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        public Builder mergeMessage(ReplyBaseOuterClass.ReplyBase value) {
            if (messageBuilder_ == null) {
                if (message_ != null) {
                    message_ =
                            ReplyBaseOuterClass.ReplyBase.newBuilder(message_).mergeFrom(value).buildPartial();
                } else {
                    message_ = value;
                }
                onChanged();
            } else {
                messageBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        public Builder clearMessage() {
            if (messageBuilder_ == null) {
                message_ = null;
                onChanged();
            } else {
                message_ = null;
                messageBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        public ReplyBaseOuterClass.ReplyBase.Builder getMessageBuilder() {

            onChanged();
            return getMessageFieldBuilder().getBuilder();
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        public ReplyBaseOuterClass.ReplyBaseOrBuilder getMessageOrBuilder() {
            if (messageBuilder_ != null) {
                return messageBuilder_.getMessageOrBuilder();
            } else {
                return message_ == null ?
                        ReplyBaseOuterClass.ReplyBase.getDefaultInstance() : message_;
            }
        }

        /**
         * <code>.ReplyBase message = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                ReplyBaseOuterClass.ReplyBase, ReplyBaseOuterClass.ReplyBase.Builder, ReplyBaseOuterClass.ReplyBaseOrBuilder>
        getMessageFieldBuilder() {
            if (messageBuilder_ == null) {
                messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        ReplyBaseOuterClass.ReplyBase, ReplyBaseOuterClass.ReplyBase.Builder, ReplyBaseOuterClass.ReplyBaseOrBuilder>(
                        getMessage(),
                        getParentForChildren(),
                        isClean());
                message_ = null;
            }
            return messageBuilder_;
        }

        /**
         * <code>int64 user_id = 2;</code>
         */
        public long getUserId() {
            return userId_;
        }

        /**
         * <code>int64 user_id = 2;</code>
         */
        public Builder setUserId(long value) {

            userId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 user_id = 2;</code>
         */
        public Builder clearUserId() {

            userId_ = 0L;
            onChanged();
            return this;
        }

        /**
         * <code>string first_name = 3;</code>
         */
        public String getFirstName() {
            Object ref = firstName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                firstName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string first_name = 3;</code>
         */
        public Builder setFirstName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            firstName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string first_name = 3;</code>
         */
        public com.google.protobuf.ByteString
        getFirstNameBytes() {
            Object ref = firstName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                firstName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string first_name = 3;</code>
         */
        public Builder setFirstNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            firstName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string first_name = 3;</code>
         */
        public Builder clearFirstName() {

            firstName_ = getDefaultInstance().getFirstName();
            onChanged();
            return this;
        }

        /**
         * <code>string last_name = 4;</code>
         */
        public String getLastName() {
            Object ref = lastName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                lastName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string last_name = 4;</code>
         */
        public Builder setLastName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            lastName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string last_name = 4;</code>
         */
        public com.google.protobuf.ByteString
        getLastNameBytes() {
            Object ref = lastName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                lastName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string last_name = 4;</code>
         */
        public Builder setLastNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            lastName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string last_name = 4;</code>
         */
        public Builder clearLastName() {

            lastName_ = getDefaultInstance().getLastName();
            onChanged();
            return this;
        }

        /**
         * <code>string phone = 5;</code>
         */
        public String getPhone() {
            Object ref = phone_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                phone_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string phone = 5;</code>
         */
        public Builder setPhone(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            phone_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string phone = 5;</code>
         */
        public com.google.protobuf.ByteString
        getPhoneBytes() {
            Object ref = phone_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                phone_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string phone = 5;</code>
         */
        public Builder setPhoneBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            phone_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string phone = 5;</code>
         */
        public Builder clearPhone() {

            phone_ = getDefaultInstance().getPhone();
            onChanged();
            return this;
        }

        /**
         * <code>string address = 6;</code>
         */
        public String getAddress() {
            Object ref = address_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                address_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string address = 6;</code>
         */
        public Builder setAddress(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            address_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string address = 6;</code>
         */
        public com.google.protobuf.ByteString
        getAddressBytes() {
            Object ref = address_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                address_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string address = 6;</code>
         */
        public Builder setAddressBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            address_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string address = 6;</code>
         */
        public Builder clearAddress() {

            address_ = getDefaultInstance().getAddress();
            onChanged();
            return this;
        }

        /**
         * <code>string card_no = 7;</code>
         */
        public String getCardNo() {
            Object ref = cardNo_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                cardNo_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string card_no = 7;</code>
         */
        public Builder setCardNo(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            cardNo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string card_no = 7;</code>
         */
        public com.google.protobuf.ByteString
        getCardNoBytes() {
            Object ref = cardNo_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                cardNo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string card_no = 7;</code>
         */
        public Builder setCardNoBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            cardNo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string card_no = 7;</code>
         */
        public Builder clearCardNo() {

            cardNo_ = getDefaultInstance().getCardNo();
            onChanged();
            return this;
        }

        /**
         * <code>string account_no = 8;</code>
         */
        public String getAccountNo() {
            Object ref = accountNo_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                accountNo_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string account_no = 8;</code>
         */
        public Builder setAccountNo(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            accountNo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string account_no = 8;</code>
         */
        public com.google.protobuf.ByteString
        getAccountNoBytes() {
            Object ref = accountNo_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                accountNo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string account_no = 8;</code>
         */
        public Builder setAccountNoBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            accountNo_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string account_no = 8;</code>
         */
        public Builder clearAccountNo() {

            accountNo_ = getDefaultInstance().getAccountNo();
            onChanged();
            return this;
        }

        /**
         * <code>string card_balance = 9;</code>
         */
        public String getCardBalance() {
            Object ref = cardBalance_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                cardBalance_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string card_balance = 9;</code>
         */
        public Builder setCardBalance(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            cardBalance_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string card_balance = 9;</code>
         */
        public com.google.protobuf.ByteString
        getCardBalanceBytes() {
            Object ref = cardBalance_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                cardBalance_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string card_balance = 9;</code>
         */
        public Builder setCardBalanceBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            cardBalance_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string card_balance = 9;</code>
         */
        public Builder clearCardBalance() {

            cardBalance_ = getDefaultInstance().getCardBalance();
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:rpc.LoginReply)
    }

}

