// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package rpc;

public interface LoginReplyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:rpc.LoginReply)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ReplyBase message = 1;</code>
     */
    boolean hasMessage();

    /**
     * <code>.ReplyBase message = 1;</code>
     */
    ReplyBaseOuterClass.ReplyBase getMessage();

    /**
     * <code>.ReplyBase message = 1;</code>
     */
    ReplyBaseOuterClass.ReplyBaseOrBuilder getMessageOrBuilder();

    /**
     * <code>int64 user_id = 2;</code>
     */
    long getUserId();

    /**
     * <code>string first_name = 3;</code>
     */
    String getFirstName();

    /**
     * <code>string first_name = 3;</code>
     */
    com.google.protobuf.ByteString
    getFirstNameBytes();

    /**
     * <code>string last_name = 4;</code>
     */
    String getLastName();

    /**
     * <code>string last_name = 4;</code>
     */
    com.google.protobuf.ByteString
    getLastNameBytes();

    /**
     * <code>string phone = 5;</code>
     */
    String getPhone();

    /**
     * <code>string phone = 5;</code>
     */
    com.google.protobuf.ByteString
    getPhoneBytes();

    /**
     * <code>string address = 6;</code>
     */
    String getAddress();

    /**
     * <code>string address = 6;</code>
     */
    com.google.protobuf.ByteString
    getAddressBytes();

    /**
     * <code>string card_no = 7;</code>
     */
    String getCardNo();

    /**
     * <code>string card_no = 7;</code>
     */
    com.google.protobuf.ByteString
    getCardNoBytes();

    /**
     * <code>string account_no = 8;</code>
     */
    String getAccountNo();

    /**
     * <code>string account_no = 8;</code>
     */
    com.google.protobuf.ByteString
    getAccountNoBytes();

    /**
     * <code>string card_balance = 9;</code>
     */
    String getCardBalance();

    /**
     * <code>string card_balance = 9;</code>
     */
    com.google.protobuf.ByteString
    getCardBalanceBytes();
}
