// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bank.proto

package rpc;

/**
 * Protobuf type {@code rpc.Response}
 */
public final class Response extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:rpc.Response)
        ResponseOrBuilder {
    public static final int STATUS_CODE_FIELD_NUMBER = 1;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    public static final int PAGE_NUMBER_FIELD_NUMBER = 3;
    public static final int TOTAL_NUMBER_FIELD_NUMBER = 4;
    public static final int RESULT_PER_PAGE_FIELD_NUMBER = 5;
    public static final int USER_CUSTOMER_TRANS_FIELD_NUMBER = 6;
    public static final int USER_LOGIN_FIELD_NUMBER = 7;
    public static final int USER_CUSTOMER_LOGS_FIELD_NUMBER = 8;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:rpc.Response)
    private static final Response DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Response>
            PARSER = new com.google.protobuf.AbstractParser<Response>() {
        public Response parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Response(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new Response();
    }

    private int statusCode_;
    private volatile Object description_;
    private int pageNumber_;
    private int totalNumber_;
    private int resultPerPage_;
    private UserCustomerTransReply userCustomerTrans_;
    private UserLoginReply userLogin_;
    private UserCustomerLogsReply userCustomerLogs_;
    private byte memoizedIsInitialized = -1;

    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Response() {
        statusCode_ = 0;
        description_ = "";
        pageNumber_ = 0;
        totalNumber_ = 0;
        resultPerPage_ = 0;
    }

    private Response(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        statusCode_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        description_ = s;
                        break;
                    }
                    case 24: {

                        pageNumber_ = input.readInt32();
                        break;
                    }
                    case 32: {

                        totalNumber_ = input.readInt32();
                        break;
                    }
                    case 40: {

                        resultPerPage_ = input.readInt32();
                        break;
                    }
                    case 50: {
                        UserCustomerTransReply.Builder subBuilder = null;
                        if (userCustomerTrans_ != null) {
                            subBuilder = userCustomerTrans_.toBuilder();
                        }
                        userCustomerTrans_ = input.readMessage(UserCustomerTransReply.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(userCustomerTrans_);
                            userCustomerTrans_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 58: {
                        UserLoginReply.Builder subBuilder = null;
                        if (userLogin_ != null) {
                            subBuilder = userLogin_.toBuilder();
                        }
                        userLogin_ = input.readMessage(UserLoginReply.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(userLogin_);
                            userLogin_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 66: {
                        UserCustomerLogsReply.Builder subBuilder = null;
                        if (userCustomerLogs_ != null) {
                            subBuilder = userCustomerLogs_.toBuilder();
                        }
                        userCustomerLogs_ = input.readMessage(UserCustomerLogsReply.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(userCustomerLogs_);
                            userCustomerLogs_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return BankProto.internal_static_rpc_Response_descriptor;
    }

    public static Response parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Response parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Response parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Response parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Response parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Response parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Response parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Response parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Response parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Response parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Response parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Response parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Response prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static Response getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Response> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return BankProto.internal_static_rpc_Response_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Response.class, Response.Builder.class);
    }

    /**
     * <code>int32 status_code = 1;</code>
     */
    public int getStatusCode() {
        return statusCode_;
    }

    /**
     * <code>string description = 2;</code>
     */
    public String getDescription() {
        Object ref = description_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            description_ = s;
            return s;
        }
    }

    /**
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
    getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            description_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>int32 page_number = 3;</code>
     */
    public int getPageNumber() {
        return pageNumber_;
    }

    /**
     * <code>int32 total_number = 4;</code>
     */
    public int getTotalNumber() {
        return totalNumber_;
    }

    /**
     * <code>int32 result_per_page = 5;</code>
     */
    public int getResultPerPage() {
        return resultPerPage_;
    }

    /**
     * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
     */
    public boolean hasUserCustomerTrans() {
        return userCustomerTrans_ != null;
    }

    /**
     * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
     */
    public UserCustomerTransReply getUserCustomerTrans() {
        return userCustomerTrans_ == null ? UserCustomerTransReply.getDefaultInstance() : userCustomerTrans_;
    }

    /**
     * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
     */
    public UserCustomerTransReplyOrBuilder getUserCustomerTransOrBuilder() {
        return getUserCustomerTrans();
    }

    /**
     * <code>.rpc.UserLoginReply user_login = 7;</code>
     */
    public boolean hasUserLogin() {
        return userLogin_ != null;
    }

    /**
     * <code>.rpc.UserLoginReply user_login = 7;</code>
     */
    public UserLoginReply getUserLogin() {
        return userLogin_ == null ? UserLoginReply.getDefaultInstance() : userLogin_;
    }

    /**
     * <code>.rpc.UserLoginReply user_login = 7;</code>
     */
    public UserLoginReplyOrBuilder getUserLoginOrBuilder() {
        return getUserLogin();
    }

    /**
     * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
     */
    public boolean hasUserCustomerLogs() {
        return userCustomerLogs_ != null;
    }

    /**
     * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
     */
    public UserCustomerLogsReply getUserCustomerLogs() {
        return userCustomerLogs_ == null ? UserCustomerLogsReply.getDefaultInstance() : userCustomerLogs_;
    }

    /**
     * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
     */
    public UserCustomerLogsReplyOrBuilder getUserCustomerLogsOrBuilder() {
        return getUserCustomerLogs();
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (statusCode_ != 0) {
            output.writeInt32(1, statusCode_);
        }
        if (!getDescriptionBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
        }
        if (pageNumber_ != 0) {
            output.writeInt32(3, pageNumber_);
        }
        if (totalNumber_ != 0) {
            output.writeInt32(4, totalNumber_);
        }
        if (resultPerPage_ != 0) {
            output.writeInt32(5, resultPerPage_);
        }
        if (userCustomerTrans_ != null) {
            output.writeMessage(6, getUserCustomerTrans());
        }
        if (userLogin_ != null) {
            output.writeMessage(7, getUserLogin());
        }
        if (userCustomerLogs_ != null) {
            output.writeMessage(8, getUserCustomerLogs());
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (statusCode_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, statusCode_);
        }
        if (!getDescriptionBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
        }
        if (pageNumber_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, pageNumber_);
        }
        if (totalNumber_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, totalNumber_);
        }
        if (resultPerPage_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(5, resultPerPage_);
        }
        if (userCustomerTrans_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(6, getUserCustomerTrans());
        }
        if (userLogin_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(7, getUserLogin());
        }
        if (userCustomerLogs_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(8, getUserCustomerLogs());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Response)) {
            return super.equals(obj);
        }
        Response other = (Response) obj;

        boolean result = true;
        result = result && (getStatusCode()
                == other.getStatusCode());
        result = result && getDescription()
                .equals(other.getDescription());
        result = result && (getPageNumber()
                == other.getPageNumber());
        result = result && (getTotalNumber()
                == other.getTotalNumber());
        result = result && (getResultPerPage()
                == other.getResultPerPage());
        result = result && (hasUserCustomerTrans() == other.hasUserCustomerTrans());
        if (hasUserCustomerTrans()) {
            result = result && getUserCustomerTrans()
                    .equals(other.getUserCustomerTrans());
        }
        result = result && (hasUserLogin() == other.hasUserLogin());
        if (hasUserLogin()) {
            result = result && getUserLogin()
                    .equals(other.getUserLogin());
        }
        result = result && (hasUserCustomerLogs() == other.hasUserCustomerLogs());
        if (hasUserCustomerLogs()) {
            result = result && getUserCustomerLogs()
                    .equals(other.getUserCustomerLogs());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getStatusCode();
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
        hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPageNumber();
        hash = (37 * hash) + TOTAL_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getTotalNumber();
        hash = (37 * hash) + RESULT_PER_PAGE_FIELD_NUMBER;
        hash = (53 * hash) + getResultPerPage();
        if (hasUserCustomerTrans()) {
            hash = (37 * hash) + USER_CUSTOMER_TRANS_FIELD_NUMBER;
            hash = (53 * hash) + getUserCustomerTrans().hashCode();
        }
        if (hasUserLogin()) {
            hash = (37 * hash) + USER_LOGIN_FIELD_NUMBER;
            hash = (53 * hash) + getUserLogin().hashCode();
        }
        if (hasUserCustomerLogs()) {
            hash = (37 * hash) + USER_CUSTOMER_LOGS_FIELD_NUMBER;
            hash = (53 * hash) + getUserCustomerLogs().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<Response> getParserForType() {
        return PARSER;
    }

    public Response getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code rpc.Response}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:rpc.Response)
            ResponseOrBuilder {
        private int statusCode_;
        private Object description_ = "";
        private int pageNumber_;
        private int totalNumber_;
        private int resultPerPage_;
        private UserCustomerTransReply userCustomerTrans_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                UserCustomerTransReply, UserCustomerTransReply.Builder, UserCustomerTransReplyOrBuilder> userCustomerTransBuilder_;
        private UserLoginReply userLogin_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                UserLoginReply, UserLoginReply.Builder, UserLoginReplyOrBuilder> userLoginBuilder_;
        private UserCustomerLogsReply userCustomerLogs_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                UserCustomerLogsReply, UserCustomerLogsReply.Builder, UserCustomerLogsReplyOrBuilder> userCustomerLogsBuilder_;

        // Construct using rpc.Response.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return BankProto.internal_static_rpc_Response_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return BankProto.internal_static_rpc_Response_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Response.class, Response.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            statusCode_ = 0;

            description_ = "";

            pageNumber_ = 0;

            totalNumber_ = 0;

            resultPerPage_ = 0;

            if (userCustomerTransBuilder_ == null) {
                userCustomerTrans_ = null;
            } else {
                userCustomerTrans_ = null;
                userCustomerTransBuilder_ = null;
            }
            if (userLoginBuilder_ == null) {
                userLogin_ = null;
            } else {
                userLogin_ = null;
                userLoginBuilder_ = null;
            }
            if (userCustomerLogsBuilder_ == null) {
                userCustomerLogs_ = null;
            } else {
                userCustomerLogs_ = null;
                userCustomerLogsBuilder_ = null;
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return BankProto.internal_static_rpc_Response_descriptor;
        }

        public Response getDefaultInstanceForType() {
            return Response.getDefaultInstance();
        }

        public Response build() {
            Response result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public Response buildPartial() {
            Response result = new Response(this);
            result.statusCode_ = statusCode_;
            result.description_ = description_;
            result.pageNumber_ = pageNumber_;
            result.totalNumber_ = totalNumber_;
            result.resultPerPage_ = resultPerPage_;
            if (userCustomerTransBuilder_ == null) {
                result.userCustomerTrans_ = userCustomerTrans_;
            } else {
                result.userCustomerTrans_ = userCustomerTransBuilder_.build();
            }
            if (userLoginBuilder_ == null) {
                result.userLogin_ = userLogin_;
            } else {
                result.userLogin_ = userLoginBuilder_.build();
            }
            if (userCustomerLogsBuilder_ == null) {
                result.userCustomerLogs_ = userCustomerLogs_;
            } else {
                result.userCustomerLogs_ = userCustomerLogsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Response) {
                return mergeFrom((Response) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Response other) {
            if (other == Response.getDefaultInstance()) return this;
            if (other.getStatusCode() != 0) {
                setStatusCode(other.getStatusCode());
            }
            if (!other.getDescription().isEmpty()) {
                description_ = other.description_;
                onChanged();
            }
            if (other.getPageNumber() != 0) {
                setPageNumber(other.getPageNumber());
            }
            if (other.getTotalNumber() != 0) {
                setTotalNumber(other.getTotalNumber());
            }
            if (other.getResultPerPage() != 0) {
                setResultPerPage(other.getResultPerPage());
            }
            if (other.hasUserCustomerTrans()) {
                mergeUserCustomerTrans(other.getUserCustomerTrans());
            }
            if (other.hasUserLogin()) {
                mergeUserLogin(other.getUserLogin());
            }
            if (other.hasUserCustomerLogs()) {
                mergeUserCustomerLogs(other.getUserCustomerLogs());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Response parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Response) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int32 status_code = 1;</code>
         */
        public int getStatusCode() {
            return statusCode_;
        }

        /**
         * <code>int32 status_code = 1;</code>
         */
        public Builder setStatusCode(int value) {

            statusCode_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 status_code = 1;</code>
         */
        public Builder clearStatusCode() {

            statusCode_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>string description = 2;</code>
         */
        public String getDescription() {
            Object ref = description_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                description_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string description = 2;</code>
         */
        public Builder setDescription(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            description_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string description = 2;</code>
         */
        public com.google.protobuf.ByteString
        getDescriptionBytes() {
            Object ref = description_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                description_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string description = 2;</code>
         */
        public Builder setDescriptionBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            description_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string description = 2;</code>
         */
        public Builder clearDescription() {

            description_ = getDefaultInstance().getDescription();
            onChanged();
            return this;
        }

        /**
         * <code>int32 page_number = 3;</code>
         */
        public int getPageNumber() {
            return pageNumber_;
        }

        /**
         * <code>int32 page_number = 3;</code>
         */
        public Builder setPageNumber(int value) {

            pageNumber_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 page_number = 3;</code>
         */
        public Builder clearPageNumber() {

            pageNumber_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>int32 total_number = 4;</code>
         */
        public int getTotalNumber() {
            return totalNumber_;
        }

        /**
         * <code>int32 total_number = 4;</code>
         */
        public Builder setTotalNumber(int value) {

            totalNumber_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 total_number = 4;</code>
         */
        public Builder clearTotalNumber() {

            totalNumber_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>int32 result_per_page = 5;</code>
         */
        public int getResultPerPage() {
            return resultPerPage_;
        }

        /**
         * <code>int32 result_per_page = 5;</code>
         */
        public Builder setResultPerPage(int value) {

            resultPerPage_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 result_per_page = 5;</code>
         */
        public Builder clearResultPerPage() {

            resultPerPage_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        public boolean hasUserCustomerTrans() {
            return userCustomerTransBuilder_ != null || userCustomerTrans_ != null;
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        public UserCustomerTransReply getUserCustomerTrans() {
            if (userCustomerTransBuilder_ == null) {
                return userCustomerTrans_ == null ? UserCustomerTransReply.getDefaultInstance() : userCustomerTrans_;
            } else {
                return userCustomerTransBuilder_.getMessage();
            }
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        public Builder setUserCustomerTrans(
                UserCustomerTransReply.Builder builderForValue) {
            if (userCustomerTransBuilder_ == null) {
                userCustomerTrans_ = builderForValue.build();
                onChanged();
            } else {
                userCustomerTransBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        public Builder setUserCustomerTrans(UserCustomerTransReply value) {
            if (userCustomerTransBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                userCustomerTrans_ = value;
                onChanged();
            } else {
                userCustomerTransBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        public Builder mergeUserCustomerTrans(UserCustomerTransReply value) {
            if (userCustomerTransBuilder_ == null) {
                if (userCustomerTrans_ != null) {
                    userCustomerTrans_ =
                            UserCustomerTransReply.newBuilder(userCustomerTrans_).mergeFrom(value).buildPartial();
                } else {
                    userCustomerTrans_ = value;
                }
                onChanged();
            } else {
                userCustomerTransBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        public Builder clearUserCustomerTrans() {
            if (userCustomerTransBuilder_ == null) {
                userCustomerTrans_ = null;
                onChanged();
            } else {
                userCustomerTrans_ = null;
                userCustomerTransBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        public UserCustomerTransReply.Builder getUserCustomerTransBuilder() {

            onChanged();
            return getUserCustomerTransFieldBuilder().getBuilder();
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        public UserCustomerTransReplyOrBuilder getUserCustomerTransOrBuilder() {
            if (userCustomerTransBuilder_ != null) {
                return userCustomerTransBuilder_.getMessageOrBuilder();
            } else {
                return userCustomerTrans_ == null ?
                        UserCustomerTransReply.getDefaultInstance() : userCustomerTrans_;
            }
        }

        /**
         * <code>.rpc.UserCustomerTransReply user_customer_trans = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                UserCustomerTransReply, UserCustomerTransReply.Builder, UserCustomerTransReplyOrBuilder>
        getUserCustomerTransFieldBuilder() {
            if (userCustomerTransBuilder_ == null) {
                userCustomerTransBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        UserCustomerTransReply, UserCustomerTransReply.Builder, UserCustomerTransReplyOrBuilder>(
                        getUserCustomerTrans(),
                        getParentForChildren(),
                        isClean());
                userCustomerTrans_ = null;
            }
            return userCustomerTransBuilder_;
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        public boolean hasUserLogin() {
            return userLoginBuilder_ != null || userLogin_ != null;
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        public UserLoginReply getUserLogin() {
            if (userLoginBuilder_ == null) {
                return userLogin_ == null ? UserLoginReply.getDefaultInstance() : userLogin_;
            } else {
                return userLoginBuilder_.getMessage();
            }
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        public Builder setUserLogin(
                UserLoginReply.Builder builderForValue) {
            if (userLoginBuilder_ == null) {
                userLogin_ = builderForValue.build();
                onChanged();
            } else {
                userLoginBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        public Builder setUserLogin(UserLoginReply value) {
            if (userLoginBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                userLogin_ = value;
                onChanged();
            } else {
                userLoginBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        public Builder mergeUserLogin(UserLoginReply value) {
            if (userLoginBuilder_ == null) {
                if (userLogin_ != null) {
                    userLogin_ =
                            UserLoginReply.newBuilder(userLogin_).mergeFrom(value).buildPartial();
                } else {
                    userLogin_ = value;
                }
                onChanged();
            } else {
                userLoginBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        public Builder clearUserLogin() {
            if (userLoginBuilder_ == null) {
                userLogin_ = null;
                onChanged();
            } else {
                userLogin_ = null;
                userLoginBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        public UserLoginReply.Builder getUserLoginBuilder() {

            onChanged();
            return getUserLoginFieldBuilder().getBuilder();
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        public UserLoginReplyOrBuilder getUserLoginOrBuilder() {
            if (userLoginBuilder_ != null) {
                return userLoginBuilder_.getMessageOrBuilder();
            } else {
                return userLogin_ == null ?
                        UserLoginReply.getDefaultInstance() : userLogin_;
            }
        }

        /**
         * <code>.rpc.UserLoginReply user_login = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                UserLoginReply, UserLoginReply.Builder, UserLoginReplyOrBuilder>
        getUserLoginFieldBuilder() {
            if (userLoginBuilder_ == null) {
                userLoginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        UserLoginReply, UserLoginReply.Builder, UserLoginReplyOrBuilder>(
                        getUserLogin(),
                        getParentForChildren(),
                        isClean());
                userLogin_ = null;
            }
            return userLoginBuilder_;
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        public boolean hasUserCustomerLogs() {
            return userCustomerLogsBuilder_ != null || userCustomerLogs_ != null;
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        public UserCustomerLogsReply getUserCustomerLogs() {
            if (userCustomerLogsBuilder_ == null) {
                return userCustomerLogs_ == null ? UserCustomerLogsReply.getDefaultInstance() : userCustomerLogs_;
            } else {
                return userCustomerLogsBuilder_.getMessage();
            }
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        public Builder setUserCustomerLogs(
                UserCustomerLogsReply.Builder builderForValue) {
            if (userCustomerLogsBuilder_ == null) {
                userCustomerLogs_ = builderForValue.build();
                onChanged();
            } else {
                userCustomerLogsBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        public Builder setUserCustomerLogs(UserCustomerLogsReply value) {
            if (userCustomerLogsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                userCustomerLogs_ = value;
                onChanged();
            } else {
                userCustomerLogsBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        public Builder mergeUserCustomerLogs(UserCustomerLogsReply value) {
            if (userCustomerLogsBuilder_ == null) {
                if (userCustomerLogs_ != null) {
                    userCustomerLogs_ =
                            UserCustomerLogsReply.newBuilder(userCustomerLogs_).mergeFrom(value).buildPartial();
                } else {
                    userCustomerLogs_ = value;
                }
                onChanged();
            } else {
                userCustomerLogsBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        public Builder clearUserCustomerLogs() {
            if (userCustomerLogsBuilder_ == null) {
                userCustomerLogs_ = null;
                onChanged();
            } else {
                userCustomerLogs_ = null;
                userCustomerLogsBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        public UserCustomerLogsReply.Builder getUserCustomerLogsBuilder() {

            onChanged();
            return getUserCustomerLogsFieldBuilder().getBuilder();
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        public UserCustomerLogsReplyOrBuilder getUserCustomerLogsOrBuilder() {
            if (userCustomerLogsBuilder_ != null) {
                return userCustomerLogsBuilder_.getMessageOrBuilder();
            } else {
                return userCustomerLogs_ == null ?
                        UserCustomerLogsReply.getDefaultInstance() : userCustomerLogs_;
            }
        }

        /**
         * <code>.rpc.UserCustomerLogsReply user_customer_logs = 8;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                UserCustomerLogsReply, UserCustomerLogsReply.Builder, UserCustomerLogsReplyOrBuilder>
        getUserCustomerLogsFieldBuilder() {
            if (userCustomerLogsBuilder_ == null) {
                userCustomerLogsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        UserCustomerLogsReply, UserCustomerLogsReply.Builder, UserCustomerLogsReplyOrBuilder>(
                        getUserCustomerLogs(),
                        getParentForChildren(),
                        isClean());
                userCustomerLogs_ = null;
            }
            return userCustomerLogsBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:rpc.Response)
    }

}

