// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bank.proto

package rpc;

public interface UserRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:rpc.UserRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 user_id = 1;</code>
     */
    long getUserId();
}
