// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package rpc;

public interface UserCustomerLogsReplyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:rpc.UserCustomerLogsReply)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ReplyBase base = 1;</code>
     */
    boolean hasBase();

    /**
     * <code>.ReplyBase base = 1;</code>
     */
    ReplyBaseOuterClass.ReplyBase getBase();

    /**
     * <code>.ReplyBase base = 1;</code>
     */
    ReplyBaseOuterClass.ReplyBaseOrBuilder getBaseOrBuilder();

    /**
     * <code>repeated .rpc.UserCustomerLog trans = 2;</code>
     */
    java.util.List<rpc.UserCustomerLog>
    getTransList();

    /**
     * <code>repeated .rpc.UserCustomerLog trans = 2;</code>
     */
    rpc.UserCustomerLog getTrans(int index);

    /**
     * <code>repeated .rpc.UserCustomerLog trans = 2;</code>
     */
    int getTransCount();

    /**
     * <code>repeated .rpc.UserCustomerLog trans = 2;</code>
     */
    java.util.List<? extends rpc.UserCustomerLogOrBuilder>
    getTransOrBuilderList();

    /**
     * <code>repeated .rpc.UserCustomerLog trans = 2;</code>
     */
    rpc.UserCustomerLogOrBuilder getTransOrBuilder(
            int index);
}
