// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package rpc;

public final class UserCustomerProto {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_UserCustomerEditRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_rpc_UserCustomerEditRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_UserCustomerTran_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_rpc_UserCustomerTran_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_UserCustomerTransReply_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_rpc_UserCustomerTransReply_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_UserCustomerLog_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_rpc_UserCustomerLog_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_UserCustomerLogsReply_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_rpc_UserCustomerLogsReply_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_rpc_UserCustomerTranRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_rpc_UserCustomerTranRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\016customer.proto\022\003rpc\032\017ReplyBase.proto\032\021" +
                        "UserRequest.proto\"J\n\027UserCustomerEditReq" +
                        "uest\022\017\n\007user_id\030\001 \001(\t\022\r\n\005phone\030\002 \001(\t\022\017\n\007" +
                        "address\030\003 \001(\t\"\205\001\n\020UserCustomerTran\022\020\n\010tr" +
                        "ans_id\030\001 \001(\003\022\020\n\010trans_no\030\002 \001(\t\022\024\n\014from_c" +
                        "ard_no\030\003 \001(\t\022\022\n\nto_card_no\030\004 \001(\t\022\023\n\013desc" +
                        "ription\030\005 \001(\t\022\016\n\006status\030\006 \001(\005\"X\n\026UserCus" +
                        "tomerTransReply\022\030\n\004base\030\001 \001(\0132\n.ReplyBas" +
                        "e\022$\n\005trans\030\002 \003(\0132\025.rpc.UserCustomerTran\"" +
                        "\227\001\n\017UserCustomerLog\022\016\n\006log_id\030\001 \001(\003\022\024\n\014o" +
                        "perate_type\030\002 \001(\005\022\024\n\014operate_time\030\003 \001(\t\022" +
                        "\023\n\013description\030\004 \001(\t\022\016\n\006status\030\005 \001(\005\022#\n\004" +
                        "tran\030\006 \001(\0132\025.rpc.UserCustomerTran\"V\n\025Use" +
                        "rCustomerLogsReply\022\030\n\004base\030\001 \001(\0132\n.Reply" +
                        "Base\022#\n\005trans\030\002 \003(\0132\024.rpc.UserCustomerLo" +
                        "g\"u\n\027UserCustomerTranRequest\022\017\n\007user_id\030" +
                        "\001 \001(\t\022\022\n\nto_card_no\030\002 \001(\t\022\016\n\006amount\030\003 \001(" +
                        "\t\022\020\n\010currency\030\004 \001(\t\022\023\n\013description\030\005 \001(\t" +
                        "2\274\002\n\014UserCustomer\0229\n\rEditUserPhone\022\034.rpc" +
                        ".UserCustomerEditRequest\032\n.ReplyBase\022;\n\017" +
                        "EditUserAddress\022\034.rpc.UserCustomerEditRe" +
                        "quest\032\n.ReplyBase\022?\n\022GetUserTransaction\022" +
                        "\014.UserRequest\032\033.rpc.UserCustomerTransRep" +
                        "ly\022=\n\021GetUserOperateLog\022\014.UserRequest\032\032." +
                        "rpc.UserCustomerLogsReply\0224\n\010MakeTran\022\034." +
                        "rpc.UserCustomerTranRequest\032\n.ReplyBaseB" +
                        " \n\003rpcB\021UserCustomerProtoP\001\242\002\003HLWb\006proto" +
                        "3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                ReplyBaseOuterClass.getDescriptor(),
                                UserRequestOuterClass.getDescriptor(),
                        }, assigner);
        internal_static_rpc_UserCustomerEditRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_rpc_UserCustomerEditRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_rpc_UserCustomerEditRequest_descriptor,
                new String[]{"UserId", "Phone", "Address",});
        internal_static_rpc_UserCustomerTran_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_rpc_UserCustomerTran_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_rpc_UserCustomerTran_descriptor,
                new String[]{"TransId", "TransNo", "FromCardNo", "ToCardNo", "Description", "Status",});
        internal_static_rpc_UserCustomerTransReply_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_rpc_UserCustomerTransReply_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_rpc_UserCustomerTransReply_descriptor,
                new String[]{"Base", "Trans",});
        internal_static_rpc_UserCustomerLog_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_rpc_UserCustomerLog_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_rpc_UserCustomerLog_descriptor,
                new String[]{"LogId", "OperateType", "OperateTime", "Description", "Status", "Tran",});
        internal_static_rpc_UserCustomerLogsReply_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_rpc_UserCustomerLogsReply_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_rpc_UserCustomerLogsReply_descriptor,
                new String[]{"Base", "Trans",});
        internal_static_rpc_UserCustomerTranRequest_descriptor =
                getDescriptor().getMessageTypes().get(5);
        internal_static_rpc_UserCustomerTranRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_rpc_UserCustomerTranRequest_descriptor,
                new String[]{"UserId", "ToCardNo", "Amount", "Currency", "Description",});
        ReplyBaseOuterClass.getDescriptor();
        UserRequestOuterClass.getDescriptor();
    }

    private UserCustomerProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
