// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package rpc;

public interface UserCustomerEditRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:rpc.UserCustomerEditRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id = 1;</code>
     */
    String getUserId();

    /**
     * <code>string user_id = 1;</code>
     */
    com.google.protobuf.ByteString
    getUserIdBytes();

    /**
     * <code>string phone = 2;</code>
     */
    String getPhone();

    /**
     * <code>string phone = 2;</code>
     */
    com.google.protobuf.ByteString
    getPhoneBytes();

    /**
     * <code>string address = 3;</code>
     */
    String getAddress();

    /**
     * <code>string address = 3;</code>
     */
    com.google.protobuf.ByteString
    getAddressBytes();
}
