// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bank.proto

package rpc;

/**
 * Protobuf type {@code rpc.UserAdminRequest}
 */
public final class UserAdminRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:rpc.UserAdminRequest)
        UserAdminRequestOrBuilder {
    public static final int USERNAME_FIELD_NUMBER = 1;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    public static final int STAFF_FIRST_NAME_FIELD_NUMBER = 3;
    public static final int STAFF_LAST_NAME_FIELD_NUMBER = 4;
    public static final int STAFF_EMAIL_FIELD_NUMBER = 5;
    public static final int STAFF_ID_FIELD_NUMBER = 6;
    public static final int EMAIL_HOST_FIELD_NUMBER = 7;
    public static final int EMAIL_PORT_FIELD_NUMBER = 8;
    public static final int EMAIL_ACCOUNT_FIELD_NUMBER = 9;
    public static final int EMAIL_PASSWORD_FIELD_NUMBER = 10;
    public static final int FILTER_BY_ID_NAME_FIELD_NUMBER = 11;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:rpc.UserAdminRequest)
    private static final UserAdminRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<UserAdminRequest>
            PARSER = new com.google.protobuf.AbstractParser<UserAdminRequest>() {
        public UserAdminRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new UserAdminRequest(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new UserAdminRequest();
    }

    private volatile Object username_;
    private volatile Object password_;
    private volatile Object staffFirstName_;
    private volatile Object staffLastName_;
    private volatile Object staffEmail_;
    private volatile Object staffId_;
    private volatile Object emailHost_;
    private volatile Object emailPort_;
    private volatile Object emailAccount_;
    private volatile Object emailPassword_;
    private volatile Object filterByIdName_;
    private byte memoizedIsInitialized = -1;

    // Use UserAdminRequest.newBuilder() to construct.
    private UserAdminRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private UserAdminRequest() {
        username_ = "";
        password_ = "";
        staffFirstName_ = "";
        staffLastName_ = "";
        staffEmail_ = "";
        staffId_ = "";
        emailHost_ = "";
        emailPort_ = "";
        emailAccount_ = "";
        emailPassword_ = "";
        filterByIdName_ = "";
    }

    private UserAdminRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        username_ = s;
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        password_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        staffFirstName_ = s;
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        staffLastName_ = s;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        staffEmail_ = s;
                        break;
                    }
                    case 50: {
                        String s = input.readStringRequireUtf8();

                        staffId_ = s;
                        break;
                    }
                    case 58: {
                        String s = input.readStringRequireUtf8();

                        emailHost_ = s;
                        break;
                    }
                    case 66: {
                        String s = input.readStringRequireUtf8();

                        emailPort_ = s;
                        break;
                    }
                    case 74: {
                        String s = input.readStringRequireUtf8();

                        emailAccount_ = s;
                        break;
                    }
                    case 82: {
                        String s = input.readStringRequireUtf8();

                        emailPassword_ = s;
                        break;
                    }
                    case 90: {
                        String s = input.readStringRequireUtf8();

                        filterByIdName_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return BankProto.internal_static_rpc_UserAdminRequest_descriptor;
    }

    public static UserAdminRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UserAdminRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserAdminRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UserAdminRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserAdminRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UserAdminRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserAdminRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static UserAdminRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserAdminRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserAdminRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserAdminRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static UserAdminRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(UserAdminRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static UserAdminRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<UserAdminRequest> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return BankProto.internal_static_rpc_UserAdminRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        UserAdminRequest.class, UserAdminRequest.Builder.class);
    }

    /**
     * <code>string username = 1;</code>
     */
    public String getUsername() {
        Object ref = username_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            username_ = s;
            return s;
        }
    }

    /**
     * <code>string username = 1;</code>
     */
    public com.google.protobuf.ByteString
    getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            username_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string password = 2;</code>
     */
    public String getPassword() {
        Object ref = password_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            password_ = s;
            return s;
        }
    }

    /**
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
    getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            password_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string staff_first_name = 3;</code>
     */
    public String getStaffFirstName() {
        Object ref = staffFirstName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            staffFirstName_ = s;
            return s;
        }
    }

    /**
     * <code>string staff_first_name = 3;</code>
     */
    public com.google.protobuf.ByteString
    getStaffFirstNameBytes() {
        Object ref = staffFirstName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            staffFirstName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string staff_last_name = 4;</code>
     */
    public String getStaffLastName() {
        Object ref = staffLastName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            staffLastName_ = s;
            return s;
        }
    }

    /**
     * <code>string staff_last_name = 4;</code>
     */
    public com.google.protobuf.ByteString
    getStaffLastNameBytes() {
        Object ref = staffLastName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            staffLastName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * staff_id and password will be generated then sent to staff email.
     * </pre>
     *
     * <code>string staff_email = 5;</code>
     */
    public String getStaffEmail() {
        Object ref = staffEmail_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            staffEmail_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * staff_id and password will be generated then sent to staff email.
     * </pre>
     *
     * <code>string staff_email = 5;</code>
     */
    public com.google.protobuf.ByteString
    getStaffEmailBytes() {
        Object ref = staffEmail_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            staffEmail_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * for remove staff
     * </pre>
     *
     * <code>string staff_id = 6;</code>
     */
    public String getStaffId() {
        Object ref = staffId_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            staffId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * for remove staff
     * </pre>
     *
     * <code>string staff_id = 6;</code>
     */
    public com.google.protobuf.ByteString
    getStaffIdBytes() {
        Object ref = staffId_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            staffId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string email_host = 7;</code>
     */
    public String getEmailHost() {
        Object ref = emailHost_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            emailHost_ = s;
            return s;
        }
    }

    /**
     * <code>string email_host = 7;</code>
     */
    public com.google.protobuf.ByteString
    getEmailHostBytes() {
        Object ref = emailHost_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            emailHost_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string email_port = 8;</code>
     */
    public String getEmailPort() {
        Object ref = emailPort_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            emailPort_ = s;
            return s;
        }
    }

    /**
     * <code>string email_port = 8;</code>
     */
    public com.google.protobuf.ByteString
    getEmailPortBytes() {
        Object ref = emailPort_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            emailPort_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string email_account = 9;</code>
     */
    public String getEmailAccount() {
        Object ref = emailAccount_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            emailAccount_ = s;
            return s;
        }
    }

    /**
     * <code>string email_account = 9;</code>
     */
    public com.google.protobuf.ByteString
    getEmailAccountBytes() {
        Object ref = emailAccount_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            emailAccount_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string email_password = 10;</code>
     */
    public String getEmailPassword() {
        Object ref = emailPassword_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            emailPassword_ = s;
            return s;
        }
    }

    /**
     * <code>string email_password = 10;</code>
     */
    public com.google.protobuf.ByteString
    getEmailPasswordBytes() {
        Object ref = emailPassword_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            emailPassword_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string filter_by_id_name = 11;</code>
     */
    public String getFilterByIdName() {
        Object ref = filterByIdName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            filterByIdName_ = s;
            return s;
        }
    }

    /**
     * <code>string filter_by_id_name = 11;</code>
     */
    public com.google.protobuf.ByteString
    getFilterByIdNameBytes() {
        Object ref = filterByIdName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            filterByIdName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getUsernameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
        }
        if (!getPasswordBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
        }
        if (!getStaffFirstNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, staffFirstName_);
        }
        if (!getStaffLastNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, staffLastName_);
        }
        if (!getStaffEmailBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, staffEmail_);
        }
        if (!getStaffIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, staffId_);
        }
        if (!getEmailHostBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, emailHost_);
        }
        if (!getEmailPortBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 8, emailPort_);
        }
        if (!getEmailAccountBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 9, emailAccount_);
        }
        if (!getEmailPasswordBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 10, emailPassword_);
        }
        if (!getFilterByIdNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 11, filterByIdName_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getUsernameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
        }
        if (!getPasswordBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
        }
        if (!getStaffFirstNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, staffFirstName_);
        }
        if (!getStaffLastNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, staffLastName_);
        }
        if (!getStaffEmailBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, staffEmail_);
        }
        if (!getStaffIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, staffId_);
        }
        if (!getEmailHostBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, emailHost_);
        }
        if (!getEmailPortBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, emailPort_);
        }
        if (!getEmailAccountBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, emailAccount_);
        }
        if (!getEmailPasswordBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, emailPassword_);
        }
        if (!getFilterByIdNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, filterByIdName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof UserAdminRequest)) {
            return super.equals(obj);
        }
        UserAdminRequest other = (UserAdminRequest) obj;

        boolean result = true;
        result = result && getUsername()
                .equals(other.getUsername());
        result = result && getPassword()
                .equals(other.getPassword());
        result = result && getStaffFirstName()
                .equals(other.getStaffFirstName());
        result = result && getStaffLastName()
                .equals(other.getStaffLastName());
        result = result && getStaffEmail()
                .equals(other.getStaffEmail());
        result = result && getStaffId()
                .equals(other.getStaffId());
        result = result && getEmailHost()
                .equals(other.getEmailHost());
        result = result && getEmailPort()
                .equals(other.getEmailPort());
        result = result && getEmailAccount()
                .equals(other.getEmailAccount());
        result = result && getEmailPassword()
                .equals(other.getEmailPassword());
        result = result && getFilterByIdName()
                .equals(other.getFilterByIdName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
        hash = (37 * hash) + STAFF_FIRST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getStaffFirstName().hashCode();
        hash = (37 * hash) + STAFF_LAST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getStaffLastName().hashCode();
        hash = (37 * hash) + STAFF_EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getStaffEmail().hashCode();
        hash = (37 * hash) + STAFF_ID_FIELD_NUMBER;
        hash = (53 * hash) + getStaffId().hashCode();
        hash = (37 * hash) + EMAIL_HOST_FIELD_NUMBER;
        hash = (53 * hash) + getEmailHost().hashCode();
        hash = (37 * hash) + EMAIL_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getEmailPort().hashCode();
        hash = (37 * hash) + EMAIL_ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getEmailAccount().hashCode();
        hash = (37 * hash) + EMAIL_PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getEmailPassword().hashCode();
        hash = (37 * hash) + FILTER_BY_ID_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilterByIdName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<UserAdminRequest> getParserForType() {
        return PARSER;
    }

    public UserAdminRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code rpc.UserAdminRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:rpc.UserAdminRequest)
            UserAdminRequestOrBuilder {
        private Object username_ = "";
        private Object password_ = "";
        private Object staffFirstName_ = "";
        private Object staffLastName_ = "";
        private Object staffEmail_ = "";
        private Object staffId_ = "";
        private Object emailHost_ = "";
        private Object emailPort_ = "";
        private Object emailAccount_ = "";
        private Object emailPassword_ = "";
        private Object filterByIdName_ = "";

        // Construct using rpc.UserAdminRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return BankProto.internal_static_rpc_UserAdminRequest_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return BankProto.internal_static_rpc_UserAdminRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UserAdminRequest.class, UserAdminRequest.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            username_ = "";

            password_ = "";

            staffFirstName_ = "";

            staffLastName_ = "";

            staffEmail_ = "";

            staffId_ = "";

            emailHost_ = "";

            emailPort_ = "";

            emailAccount_ = "";

            emailPassword_ = "";

            filterByIdName_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return BankProto.internal_static_rpc_UserAdminRequest_descriptor;
        }

        public UserAdminRequest getDefaultInstanceForType() {
            return UserAdminRequest.getDefaultInstance();
        }

        public UserAdminRequest build() {
            UserAdminRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public UserAdminRequest buildPartial() {
            UserAdminRequest result = new UserAdminRequest(this);
            result.username_ = username_;
            result.password_ = password_;
            result.staffFirstName_ = staffFirstName_;
            result.staffLastName_ = staffLastName_;
            result.staffEmail_ = staffEmail_;
            result.staffId_ = staffId_;
            result.emailHost_ = emailHost_;
            result.emailPort_ = emailPort_;
            result.emailAccount_ = emailAccount_;
            result.emailPassword_ = emailPassword_;
            result.filterByIdName_ = filterByIdName_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof UserAdminRequest) {
                return mergeFrom((UserAdminRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(UserAdminRequest other) {
            if (other == UserAdminRequest.getDefaultInstance()) return this;
            if (!other.getUsername().isEmpty()) {
                username_ = other.username_;
                onChanged();
            }
            if (!other.getPassword().isEmpty()) {
                password_ = other.password_;
                onChanged();
            }
            if (!other.getStaffFirstName().isEmpty()) {
                staffFirstName_ = other.staffFirstName_;
                onChanged();
            }
            if (!other.getStaffLastName().isEmpty()) {
                staffLastName_ = other.staffLastName_;
                onChanged();
            }
            if (!other.getStaffEmail().isEmpty()) {
                staffEmail_ = other.staffEmail_;
                onChanged();
            }
            if (!other.getStaffId().isEmpty()) {
                staffId_ = other.staffId_;
                onChanged();
            }
            if (!other.getEmailHost().isEmpty()) {
                emailHost_ = other.emailHost_;
                onChanged();
            }
            if (!other.getEmailPort().isEmpty()) {
                emailPort_ = other.emailPort_;
                onChanged();
            }
            if (!other.getEmailAccount().isEmpty()) {
                emailAccount_ = other.emailAccount_;
                onChanged();
            }
            if (!other.getEmailPassword().isEmpty()) {
                emailPassword_ = other.emailPassword_;
                onChanged();
            }
            if (!other.getFilterByIdName().isEmpty()) {
                filterByIdName_ = other.filterByIdName_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            UserAdminRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (UserAdminRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>string username = 1;</code>
         */
        public String getUsername() {
            Object ref = username_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                username_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string username = 1;</code>
         */
        public Builder setUsername(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            username_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string username = 1;</code>
         */
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            Object ref = username_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string username = 1;</code>
         */
        public Builder setUsernameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            username_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string username = 1;</code>
         */
        public Builder clearUsername() {

            username_ = getDefaultInstance().getUsername();
            onChanged();
            return this;
        }

        /**
         * <code>string password = 2;</code>
         */
        public String getPassword() {
            Object ref = password_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                password_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string password = 2;</code>
         */
        public Builder setPassword(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            password_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string password = 2;</code>
         */
        public com.google.protobuf.ByteString
        getPasswordBytes() {
            Object ref = password_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string password = 2;</code>
         */
        public Builder setPasswordBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            password_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string password = 2;</code>
         */
        public Builder clearPassword() {

            password_ = getDefaultInstance().getPassword();
            onChanged();
            return this;
        }

        /**
         * <code>string staff_first_name = 3;</code>
         */
        public String getStaffFirstName() {
            Object ref = staffFirstName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                staffFirstName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string staff_first_name = 3;</code>
         */
        public Builder setStaffFirstName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            staffFirstName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string staff_first_name = 3;</code>
         */
        public com.google.protobuf.ByteString
        getStaffFirstNameBytes() {
            Object ref = staffFirstName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                staffFirstName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string staff_first_name = 3;</code>
         */
        public Builder setStaffFirstNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            staffFirstName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string staff_first_name = 3;</code>
         */
        public Builder clearStaffFirstName() {

            staffFirstName_ = getDefaultInstance().getStaffFirstName();
            onChanged();
            return this;
        }

        /**
         * <code>string staff_last_name = 4;</code>
         */
        public String getStaffLastName() {
            Object ref = staffLastName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                staffLastName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string staff_last_name = 4;</code>
         */
        public Builder setStaffLastName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            staffLastName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string staff_last_name = 4;</code>
         */
        public com.google.protobuf.ByteString
        getStaffLastNameBytes() {
            Object ref = staffLastName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                staffLastName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string staff_last_name = 4;</code>
         */
        public Builder setStaffLastNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            staffLastName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string staff_last_name = 4;</code>
         */
        public Builder clearStaffLastName() {

            staffLastName_ = getDefaultInstance().getStaffLastName();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * staff_id and password will be generated then sent to staff email.
         * </pre>
         *
         * <code>string staff_email = 5;</code>
         */
        public String getStaffEmail() {
            Object ref = staffEmail_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                staffEmail_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * staff_id and password will be generated then sent to staff email.
         * </pre>
         *
         * <code>string staff_email = 5;</code>
         */
        public Builder setStaffEmail(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            staffEmail_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * staff_id and password will be generated then sent to staff email.
         * </pre>
         *
         * <code>string staff_email = 5;</code>
         */
        public com.google.protobuf.ByteString
        getStaffEmailBytes() {
            Object ref = staffEmail_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                staffEmail_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * staff_id and password will be generated then sent to staff email.
         * </pre>
         *
         * <code>string staff_email = 5;</code>
         */
        public Builder setStaffEmailBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            staffEmail_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * staff_id and password will be generated then sent to staff email.
         * </pre>
         *
         * <code>string staff_email = 5;</code>
         */
        public Builder clearStaffEmail() {

            staffEmail_ = getDefaultInstance().getStaffEmail();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * for remove staff
         * </pre>
         *
         * <code>string staff_id = 6;</code>
         */
        public String getStaffId() {
            Object ref = staffId_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                staffId_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * for remove staff
         * </pre>
         *
         * <code>string staff_id = 6;</code>
         */
        public Builder setStaffId(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            staffId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * for remove staff
         * </pre>
         *
         * <code>string staff_id = 6;</code>
         */
        public com.google.protobuf.ByteString
        getStaffIdBytes() {
            Object ref = staffId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                staffId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * for remove staff
         * </pre>
         *
         * <code>string staff_id = 6;</code>
         */
        public Builder setStaffIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            staffId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * for remove staff
         * </pre>
         *
         * <code>string staff_id = 6;</code>
         */
        public Builder clearStaffId() {

            staffId_ = getDefaultInstance().getStaffId();
            onChanged();
            return this;
        }

        /**
         * <code>string email_host = 7;</code>
         */
        public String getEmailHost() {
            Object ref = emailHost_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                emailHost_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string email_host = 7;</code>
         */
        public Builder setEmailHost(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            emailHost_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email_host = 7;</code>
         */
        public com.google.protobuf.ByteString
        getEmailHostBytes() {
            Object ref = emailHost_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                emailHost_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string email_host = 7;</code>
         */
        public Builder setEmailHostBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            emailHost_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email_host = 7;</code>
         */
        public Builder clearEmailHost() {

            emailHost_ = getDefaultInstance().getEmailHost();
            onChanged();
            return this;
        }

        /**
         * <code>string email_port = 8;</code>
         */
        public String getEmailPort() {
            Object ref = emailPort_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                emailPort_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string email_port = 8;</code>
         */
        public Builder setEmailPort(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            emailPort_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email_port = 8;</code>
         */
        public com.google.protobuf.ByteString
        getEmailPortBytes() {
            Object ref = emailPort_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                emailPort_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string email_port = 8;</code>
         */
        public Builder setEmailPortBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            emailPort_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email_port = 8;</code>
         */
        public Builder clearEmailPort() {

            emailPort_ = getDefaultInstance().getEmailPort();
            onChanged();
            return this;
        }

        /**
         * <code>string email_account = 9;</code>
         */
        public String getEmailAccount() {
            Object ref = emailAccount_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                emailAccount_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string email_account = 9;</code>
         */
        public Builder setEmailAccount(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            emailAccount_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email_account = 9;</code>
         */
        public com.google.protobuf.ByteString
        getEmailAccountBytes() {
            Object ref = emailAccount_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                emailAccount_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string email_account = 9;</code>
         */
        public Builder setEmailAccountBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            emailAccount_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email_account = 9;</code>
         */
        public Builder clearEmailAccount() {

            emailAccount_ = getDefaultInstance().getEmailAccount();
            onChanged();
            return this;
        }

        /**
         * <code>string email_password = 10;</code>
         */
        public String getEmailPassword() {
            Object ref = emailPassword_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                emailPassword_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string email_password = 10;</code>
         */
        public Builder setEmailPassword(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            emailPassword_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email_password = 10;</code>
         */
        public com.google.protobuf.ByteString
        getEmailPasswordBytes() {
            Object ref = emailPassword_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                emailPassword_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string email_password = 10;</code>
         */
        public Builder setEmailPasswordBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            emailPassword_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email_password = 10;</code>
         */
        public Builder clearEmailPassword() {

            emailPassword_ = getDefaultInstance().getEmailPassword();
            onChanged();
            return this;
        }

        /**
         * <code>string filter_by_id_name = 11;</code>
         */
        public String getFilterByIdName() {
            Object ref = filterByIdName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                filterByIdName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string filter_by_id_name = 11;</code>
         */
        public Builder setFilterByIdName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            filterByIdName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string filter_by_id_name = 11;</code>
         */
        public com.google.protobuf.ByteString
        getFilterByIdNameBytes() {
            Object ref = filterByIdName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                filterByIdName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string filter_by_id_name = 11;</code>
         */
        public Builder setFilterByIdNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            filterByIdName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string filter_by_id_name = 11;</code>
         */
        public Builder clearFilterByIdName() {

            filterByIdName_ = getDefaultInstance().getFilterByIdName();
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:rpc.UserAdminRequest)
    }

}

