// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bank.proto

package rpc;

/**
 * Protobuf type {@code rpc.UserCustomerLog}
 */
public final class UserCustomerLog extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:rpc.UserCustomerLog)
        UserCustomerLogOrBuilder {
    public static final int LOG_ID_FIELD_NUMBER = 1;
    public static final int OPERATE_TYPE_FIELD_NUMBER = 2;
    public static final int OPERATE_TIME_FIELD_NUMBER = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    public static final int STATUS_FIELD_NUMBER = 5;
    public static final int TRAN_FIELD_NUMBER = 6;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:rpc.UserCustomerLog)
    private static final UserCustomerLog DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<UserCustomerLog>
            PARSER = new com.google.protobuf.AbstractParser<UserCustomerLog>() {
        public UserCustomerLog parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new UserCustomerLog(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new UserCustomerLog();
    }

    private long logId_;
    private int operateType_;
    private volatile Object operateTime_;
    private volatile Object description_;
    private int status_;
    private UserCustomerTran tran_;
    private byte memoizedIsInitialized = -1;

    // Use UserCustomerLog.newBuilder() to construct.
    private UserCustomerLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private UserCustomerLog() {
        logId_ = 0L;
        operateType_ = 0;
        operateTime_ = "";
        description_ = "";
        status_ = 0;
    }

    private UserCustomerLog(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        logId_ = input.readInt64();
                        break;
                    }
                    case 16: {

                        operateType_ = input.readInt32();
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        operateTime_ = s;
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        description_ = s;
                        break;
                    }
                    case 40: {

                        status_ = input.readInt32();
                        break;
                    }
                    case 50: {
                        UserCustomerTran.Builder subBuilder = null;
                        if (tran_ != null) {
                            subBuilder = tran_.toBuilder();
                        }
                        tran_ = input.readMessage(UserCustomerTran.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(tran_);
                            tran_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return BankProto.internal_static_rpc_UserCustomerLog_descriptor;
    }

    public static UserCustomerLog parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UserCustomerLog parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserCustomerLog parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UserCustomerLog parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserCustomerLog parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UserCustomerLog parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UserCustomerLog parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static UserCustomerLog parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserCustomerLog parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserCustomerLog parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserCustomerLog parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static UserCustomerLog parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(UserCustomerLog prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static UserCustomerLog getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<UserCustomerLog> parser() {
        return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return BankProto.internal_static_rpc_UserCustomerLog_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        UserCustomerLog.class, UserCustomerLog.Builder.class);
    }

    /**
     * <code>int64 log_id = 1;</code>
     */
    public long getLogId() {
        return logId_;
    }

    /**
     * <code>int32 operate_type = 2;</code>
     */
    public int getOperateType() {
        return operateType_;
    }

    /**
     * <code>string operate_time = 3;</code>
     */
    public String getOperateTime() {
        Object ref = operateTime_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            operateTime_ = s;
            return s;
        }
    }

    /**
     * <code>string operate_time = 3;</code>
     */
    public com.google.protobuf.ByteString
    getOperateTimeBytes() {
        Object ref = operateTime_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            operateTime_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string description = 4;</code>
     */
    public String getDescription() {
        Object ref = description_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            description_ = s;
            return s;
        }
    }

    /**
     * <code>string description = 4;</code>
     */
    public com.google.protobuf.ByteString
    getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            description_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>int32 status = 5;</code>
     */
    public int getStatus() {
        return status_;
    }

    /**
     * <code>.rpc.UserCustomerTran tran = 6;</code>
     */
    public boolean hasTran() {
        return tran_ != null;
    }

    /**
     * <code>.rpc.UserCustomerTran tran = 6;</code>
     */
    public UserCustomerTran getTran() {
        return tran_ == null ? UserCustomerTran.getDefaultInstance() : tran_;
    }

    /**
     * <code>.rpc.UserCustomerTran tran = 6;</code>
     */
    public UserCustomerTranOrBuilder getTranOrBuilder() {
        return getTran();
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (logId_ != 0L) {
            output.writeInt64(1, logId_);
        }
        if (operateType_ != 0) {
            output.writeInt32(2, operateType_);
        }
        if (!getOperateTimeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, operateTime_);
        }
        if (!getDescriptionBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
        }
        if (status_ != 0) {
            output.writeInt32(5, status_);
        }
        if (tran_ != null) {
            output.writeMessage(6, getTran());
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (logId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, logId_);
        }
        if (operateType_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, operateType_);
        }
        if (!getOperateTimeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, operateTime_);
        }
        if (!getDescriptionBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
        }
        if (status_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(5, status_);
        }
        if (tran_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(6, getTran());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof UserCustomerLog)) {
            return super.equals(obj);
        }
        UserCustomerLog other = (UserCustomerLog) obj;

        boolean result = true;
        result = result && (getLogId()
                == other.getLogId());
        result = result && (getOperateType()
                == other.getOperateType());
        result = result && getOperateTime()
                .equals(other.getOperateTime());
        result = result && getDescription()
                .equals(other.getDescription());
        result = result && (getStatus()
                == other.getStatus());
        result = result && (hasTran() == other.hasTran());
        if (hasTran()) {
            result = result && getTran()
                    .equals(other.getTran());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + LOG_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getLogId());
        hash = (37 * hash) + OPERATE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getOperateType();
        hash = (37 * hash) + OPERATE_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getOperateTime().hashCode();
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
        if (hasTran()) {
            hash = (37 * hash) + TRAN_FIELD_NUMBER;
            hash = (53 * hash) + getTran().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public com.google.protobuf.Parser<UserCustomerLog> getParserForType() {
        return PARSER;
    }

    public UserCustomerLog getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code rpc.UserCustomerLog}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:rpc.UserCustomerLog)
            UserCustomerLogOrBuilder {
        private long logId_;
        private int operateType_;
        private Object operateTime_ = "";
        private Object description_ = "";
        private int status_;
        private UserCustomerTran tran_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                UserCustomerTran, UserCustomerTran.Builder, UserCustomerTranOrBuilder> tranBuilder_;

        // Construct using rpc.UserCustomerLog.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return BankProto.internal_static_rpc_UserCustomerLog_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return BankProto.internal_static_rpc_UserCustomerLog_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        UserCustomerLog.class, UserCustomerLog.Builder.class);
    }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            logId_ = 0L;

            operateType_ = 0;

            operateTime_ = "";

            description_ = "";

            status_ = 0;

            if (tranBuilder_ == null) {
                tran_ = null;
            } else {
                tran_ = null;
                tranBuilder_ = null;
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return BankProto.internal_static_rpc_UserCustomerLog_descriptor;
        }

        public UserCustomerLog getDefaultInstanceForType() {
            return UserCustomerLog.getDefaultInstance();
        }

        public UserCustomerLog build() {
            UserCustomerLog result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public UserCustomerLog buildPartial() {
            UserCustomerLog result = new UserCustomerLog(this);
            result.logId_ = logId_;
            result.operateType_ = operateType_;
            result.operateTime_ = operateTime_;
            result.description_ = description_;
            result.status_ = status_;
            if (tranBuilder_ == null) {
                result.tran_ = tran_;
            } else {
                result.tran_ = tranBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof UserCustomerLog) {
                return mergeFrom((UserCustomerLog) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(UserCustomerLog other) {
            if (other == UserCustomerLog.getDefaultInstance()) return this;
            if (other.getLogId() != 0L) {
                setLogId(other.getLogId());
            }
            if (other.getOperateType() != 0) {
                setOperateType(other.getOperateType());
            }
            if (!other.getOperateTime().isEmpty()) {
                operateTime_ = other.operateTime_;
                onChanged();
            }
            if (!other.getDescription().isEmpty()) {
                description_ = other.description_;
                onChanged();
            }
            if (other.getStatus() != 0) {
                setStatus(other.getStatus());
            }
            if (other.hasTran()) {
                mergeTran(other.getTran());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            UserCustomerLog parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (UserCustomerLog) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int64 log_id = 1;</code>
         */
        public long getLogId() {
            return logId_;
        }

        /**
         * <code>int64 log_id = 1;</code>
         */
        public Builder setLogId(long value) {

            logId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 log_id = 1;</code>
         */
        public Builder clearLogId() {

            logId_ = 0L;
            onChanged();
            return this;
        }

        /**
         * <code>int32 operate_type = 2;</code>
         */
        public int getOperateType() {
            return operateType_;
        }

        /**
         * <code>int32 operate_type = 2;</code>
         */
        public Builder setOperateType(int value) {

            operateType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 operate_type = 2;</code>
         */
        public Builder clearOperateType() {

            operateType_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>string operate_time = 3;</code>
         */
        public String getOperateTime() {
            Object ref = operateTime_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                operateTime_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string operate_time = 3;</code>
         */
        public Builder setOperateTime(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            operateTime_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string operate_time = 3;</code>
         */
        public com.google.protobuf.ByteString
        getOperateTimeBytes() {
            Object ref = operateTime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                operateTime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string operate_time = 3;</code>
         */
        public Builder setOperateTimeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            operateTime_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string operate_time = 3;</code>
         */
        public Builder clearOperateTime() {

            operateTime_ = getDefaultInstance().getOperateTime();
            onChanged();
            return this;
        }

        /**
         * <code>string description = 4;</code>
         */
        public String getDescription() {
            Object ref = description_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                description_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string description = 4;</code>
         */
        public Builder setDescription(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            description_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string description = 4;</code>
         */
        public com.google.protobuf.ByteString
        getDescriptionBytes() {
            Object ref = description_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                description_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string description = 4;</code>
         */
        public Builder setDescriptionBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            description_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string description = 4;</code>
         */
        public Builder clearDescription() {

            description_ = getDefaultInstance().getDescription();
            onChanged();
            return this;
        }

        /**
         * <code>int32 status = 5;</code>
         */
        public int getStatus() {
            return status_;
        }

        /**
         * <code>int32 status = 5;</code>
         */
        public Builder setStatus(int value) {

            status_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 status = 5;</code>
         */
        public Builder clearStatus() {

            status_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        public boolean hasTran() {
            return tranBuilder_ != null || tran_ != null;
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        public UserCustomerTran getTran() {
            if (tranBuilder_ == null) {
                return tran_ == null ? UserCustomerTran.getDefaultInstance() : tran_;
            } else {
                return tranBuilder_.getMessage();
            }
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        public Builder setTran(
                UserCustomerTran.Builder builderForValue) {
            if (tranBuilder_ == null) {
                tran_ = builderForValue.build();
                onChanged();
            } else {
                tranBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        public Builder setTran(UserCustomerTran value) {
            if (tranBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                tran_ = value;
                onChanged();
            } else {
                tranBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        public Builder mergeTran(UserCustomerTran value) {
            if (tranBuilder_ == null) {
                if (tran_ != null) {
                    tran_ =
                            UserCustomerTran.newBuilder(tran_).mergeFrom(value).buildPartial();
                } else {
                    tran_ = value;
                }
                onChanged();
            } else {
                tranBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        public Builder clearTran() {
            if (tranBuilder_ == null) {
                tran_ = null;
                onChanged();
            } else {
                tran_ = null;
                tranBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        public UserCustomerTran.Builder getTranBuilder() {

            onChanged();
            return getTranFieldBuilder().getBuilder();
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        public UserCustomerTranOrBuilder getTranOrBuilder() {
            if (tranBuilder_ != null) {
                return tranBuilder_.getMessageOrBuilder();
            } else {
                return tran_ == null ?
                        UserCustomerTran.getDefaultInstance() : tran_;
            }
        }

        /**
         * <code>.rpc.UserCustomerTran tran = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                UserCustomerTran, UserCustomerTran.Builder, UserCustomerTranOrBuilder>
        getTranFieldBuilder() {
            if (tranBuilder_ == null) {
                tranBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        UserCustomerTran, UserCustomerTran.Builder, UserCustomerTranOrBuilder>(
                        getTran(),
                        getParentForChildren(),
                        isClean());
                tran_ = null;
            }
            return tranBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.UserCustomerLog)
  }

}

