// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bank.proto

package rpc;

public interface UserLoginRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:rpc.UserLoginRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     */
    String getUsername();

    /**
     * <code>string username = 1;</code>
     */
    com.google.protobuf.ByteString
    getUsernameBytes();

    /**
     * <code>string password = 2;</code>
     */
    String getPassword();

    /**
     * <code>string password = 2;</code>
     */
    com.google.protobuf.ByteString
    getPasswordBytes();

    /**
     * <code>int32 role = 3;</code>
     */
    int getRole();
}
