// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bank.proto

package rpc;

/**
 * Protobuf type {@code rpc.UserCustomerTran}
 */
public final class UserCustomerTran extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:rpc.UserCustomerTran)
        UserCustomerTranOrBuilder {
  public static final int TRANS_ID_FIELD_NUMBER = 1;
  public static final int TRANS_NO_FIELD_NUMBER = 2;
  public static final int FROM_CARD_NO_FIELD_NUMBER = 3;
  public static final int TO_CARD_NO_FIELD_NUMBER = 4;
  public static final int DESCRIPTION_FIELD_NUMBER = 5;
  public static final int STATUS_FIELD_NUMBER = 6;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:rpc.UserCustomerTran)
  private static final UserCustomerTran DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<UserCustomerTran>
          PARSER = new com.google.protobuf.AbstractParser<UserCustomerTran>() {
    public UserCustomerTran parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserCustomerTran(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new UserCustomerTran();
  }

  private long transId_;
  private volatile Object transNo_;
  private volatile Object fromCardNo_;
  private volatile Object toCardNo_;
  private volatile Object description_;
  private int status_;
  private byte memoizedIsInitialized = -1;

  // Use UserCustomerTran.newBuilder() to construct.
  private UserCustomerTran(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private UserCustomerTran() {
    transId_ = 0L;
    transNo_ = "";
    fromCardNo_ = "";
    toCardNo_ = "";
    description_ = "";
    status_ = 0;
  }

  private UserCustomerTran(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            transId_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            transNo_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            fromCardNo_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            toCardNo_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 48: {

            status_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return BankProto.internal_static_rpc_UserCustomerTran_descriptor;
  }

  public static UserCustomerTran parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static UserCustomerTran parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static UserCustomerTran parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static UserCustomerTran parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static UserCustomerTran parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static UserCustomerTran parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static UserCustomerTran parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static UserCustomerTran parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static UserCustomerTran parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static UserCustomerTran parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static UserCustomerTran parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static UserCustomerTran parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(UserCustomerTran prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static UserCustomerTran getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<UserCustomerTran> parser() {
    return PARSER;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return BankProto.internal_static_rpc_UserCustomerTran_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    UserCustomerTran.class, UserCustomerTran.Builder.class);
  }

  /**
   * <code>int64 trans_id = 1;</code>
   */
  public long getTransId() {
    return transId_;
  }

  /**
   * <code>string trans_no = 2;</code>
   */
  public String getTransNo() {
    Object ref = transNo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      transNo_ = s;
      return s;
    }
  }

  /**
   * <code>string trans_no = 2;</code>
   */
  public com.google.protobuf.ByteString
  getTransNoBytes() {
    Object ref = transNo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      transNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string from_card_no = 3;</code>
   */
  public String getFromCardNo() {
    Object ref = fromCardNo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fromCardNo_ = s;
      return s;
    }
  }

  /**
   * <code>string from_card_no = 3;</code>
   */
  public com.google.protobuf.ByteString
  getFromCardNoBytes() {
    Object ref = fromCardNo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      fromCardNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string to_card_no = 4;</code>
   */
  public String getToCardNo() {
    Object ref = toCardNo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      toCardNo_ = s;
      return s;
    }
  }

  /**
   * <code>string to_card_no = 4;</code>
   */
  public com.google.protobuf.ByteString
  getToCardNoBytes() {
    Object ref = toCardNo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      toCardNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string description = 5;</code>
   */
  public String getDescription() {
    Object ref = description_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }

  /**
   * <code>string description = 5;</code>
   */
  public com.google.protobuf.ByteString
  getDescriptionBytes() {
    Object ref = description_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>int32 status = 6;</code>
   */
  public int getStatus() {
    return status_;
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (transId_ != 0L) {
      output.writeInt64(1, transId_);
    }
    if (!getTransNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transNo_);
    }
    if (!getFromCardNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromCardNo_);
    }
    if (!getToCardNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toCardNo_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
    }
    if (status_ != 0) {
      output.writeInt32(6, status_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (transId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(1, transId_);
    }
    if (!getTransNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transNo_);
    }
    if (!getFromCardNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromCardNo_);
    }
    if (!getToCardNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toCardNo_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(6, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof UserCustomerTran)) {
      return super.equals(obj);
    }
    UserCustomerTran other = (UserCustomerTran) obj;

    boolean result = true;
    result = result && (getTransId()
            == other.getTransId());
    result = result && getTransNo()
            .equals(other.getTransNo());
    result = result && getFromCardNo()
            .equals(other.getFromCardNo());
    result = result && getToCardNo()
            .equals(other.getToCardNo());
    result = result && getDescription()
            .equals(other.getDescription());
    result = result && (getStatus()
            == other.getStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANS_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTransId());
    hash = (37 * hash) + TRANS_NO_FIELD_NUMBER;
    hash = (53 * hash) + getTransNo().hashCode();
    hash = (37 * hash) + FROM_CARD_NO_FIELD_NUMBER;
    hash = (53 * hash) + getFromCardNo().hashCode();
    hash = (37 * hash) + TO_CARD_NO_FIELD_NUMBER;
    hash = (53 * hash) + getToCardNo().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {
    return newBuilder();
  }

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
          BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @Override
  public com.google.protobuf.Parser<UserCustomerTran> getParserForType() {
    return PARSER;
  }

  public UserCustomerTran getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code rpc.UserCustomerTran}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:rpc.UserCustomerTran)
          UserCustomerTranOrBuilder {
    private long transId_;
    private Object transNo_ = "";
    private Object fromCardNo_ = "";
    private Object toCardNo_ = "";
    private Object description_ = "";
    private int status_;

    // Construct using rpc.UserCustomerTran.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return BankProto.internal_static_rpc_UserCustomerTran_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return BankProto.internal_static_rpc_UserCustomerTran_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      UserCustomerTran.class, UserCustomerTran.Builder.class);
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    public Builder clear() {
      super.clear();
      transId_ = 0L;

      transNo_ = "";

      fromCardNo_ = "";

      toCardNo_ = "";

      description_ = "";

      status_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return BankProto.internal_static_rpc_UserCustomerTran_descriptor;
    }

    public UserCustomerTran getDefaultInstanceForType() {
      return UserCustomerTran.getDefaultInstance();
    }

    public UserCustomerTran build() {
      UserCustomerTran result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public UserCustomerTran buildPartial() {
      UserCustomerTran result = new UserCustomerTran(this);
      result.transId_ = transId_;
      result.transNo_ = transNo_;
      result.fromCardNo_ = fromCardNo_;
      result.toCardNo_ = toCardNo_;
      result.description_ = description_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UserCustomerTran) {
        return mergeFrom((UserCustomerTran) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UserCustomerTran other) {
      if (other == UserCustomerTran.getDefaultInstance()) return this;
      if (other.getTransId() != 0L) {
        setTransId(other.getTransId());
      }
      if (!other.getTransNo().isEmpty()) {
        transNo_ = other.transNo_;
        onChanged();
      }
      if (!other.getFromCardNo().isEmpty()) {
        fromCardNo_ = other.fromCardNo_;
        onChanged();
      }
      if (!other.getToCardNo().isEmpty()) {
        toCardNo_ = other.toCardNo_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      UserCustomerTran parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UserCustomerTran) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    /**
     * <code>int64 trans_id = 1;</code>
     */
    public long getTransId() {
      return transId_;
    }

    /**
     * <code>int64 trans_id = 1;</code>
     */
    public Builder setTransId(long value) {

      transId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int64 trans_id = 1;</code>
     */
    public Builder clearTransId() {

      transId_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>string trans_no = 2;</code>
     */
    public String getTransNo() {
      Object ref = transNo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transNo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string trans_no = 2;</code>
     */
    public Builder setTransNo(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      transNo_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string trans_no = 2;</code>
     */
    public com.google.protobuf.ByteString
    getTransNoBytes() {
      Object ref = transNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        transNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string trans_no = 2;</code>
     */
    public Builder setTransNoBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      transNo_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string trans_no = 2;</code>
     */
    public Builder clearTransNo() {

      transNo_ = getDefaultInstance().getTransNo();
      onChanged();
      return this;
    }

    /**
     * <code>string from_card_no = 3;</code>
     */
    public String getFromCardNo() {
      Object ref = fromCardNo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromCardNo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string from_card_no = 3;</code>
     */
    public Builder setFromCardNo(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      fromCardNo_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string from_card_no = 3;</code>
     */
    public com.google.protobuf.ByteString
    getFromCardNoBytes() {
      Object ref = fromCardNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        fromCardNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string from_card_no = 3;</code>
     */
    public Builder setFromCardNoBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      fromCardNo_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string from_card_no = 3;</code>
     */
    public Builder clearFromCardNo() {

      fromCardNo_ = getDefaultInstance().getFromCardNo();
      onChanged();
      return this;
    }

    /**
     * <code>string to_card_no = 4;</code>
     */
    public String getToCardNo() {
      Object ref = toCardNo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toCardNo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string to_card_no = 4;</code>
     */
    public Builder setToCardNo(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      toCardNo_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string to_card_no = 4;</code>
     */
    public com.google.protobuf.ByteString
    getToCardNoBytes() {
      Object ref = toCardNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        toCardNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string to_card_no = 4;</code>
     */
    public Builder setToCardNoBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      toCardNo_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string to_card_no = 4;</code>
     */
    public Builder clearToCardNo() {

      toCardNo_ = getDefaultInstance().getToCardNo();
      onChanged();
      return this;
    }

    /**
     * <code>string description = 5;</code>
     */
    public String getDescription() {
      Object ref = description_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string description = 5;</code>
     */
    public Builder setDescription(
            String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      description_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string description = 5;</code>
     */
    public com.google.protobuf.ByteString
    getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string description = 5;</code>
     */
    public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      description_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string description = 5;</code>
     */
    public Builder clearDescription() {

      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }

    /**
     * <code>int32 status = 6;</code>
     */
    public int getStatus() {
      return status_;
    }

    /**
     * <code>int32 status = 6;</code>
     */
    public Builder setStatus(int value) {

      status_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 status = 6;</code>
     */
    public Builder clearStatus() {

      status_ = 0;
      onChanged();
      return this;
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.UserCustomerTran)
  }

}

