// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bank.proto

package rpc;

public interface UserLoginRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:rpc.UserLoginRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id = 1;</code>
     */
    String getUserId();

    /**
     * <code>string user_id = 1;</code>
     */
    com.google.protobuf.ByteString
    getUserIdBytes();

    /**
     * <code>int32 pin1 = 2;</code>
     */
    int getPin1();

    /**
     * <code>int32 pin2 = 3;</code>
     */
    int getPin2();

    /**
     * <code>int32 pin3 = 4;</code>
     */
    int getPin3();

    /**
     * <code>int32 pin4 = 5;</code>
     */
    int getPin4();

    /**
     * <code>int32 pin5 = 6;</code>
     */
    int getPin5();

    /**
     * <code>int32 pin6 = 7;</code>
     */
    int getPin6();
}
