// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bank.proto

package rpc;

public interface UserCustomerGetPayeesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.UserCustomerGetPayeesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   */
  long getUserId();
}
